# PRESERVED SEAT EVIDENCE. Written by seat 'fable' during panel round 'dynamic_roster_and_derived_ladder_2026-10-07', at the path shown above.
# Rescued from that round's sandbox harvest, which `.gitignore` keeps out of version control; the harvest path is NOT cited here because a citation a reader cannot follow is not evidence.
# sha256 of the seat's original, before this header: 2478411aaed7d12fab36bcf9096853e9b8aae0841396922c8ef3697605ef5847
# Copied by bench/panel_sandbox.py:preserve_seat_evidence. NOT edited.
#!/usr/bin/env python3
"""FALSIFIER for scripts/measure_intra_round_correlation.py.

Imports the real module and checks the ICC(1) estimator recovers a KNOWN
intra-round correlation from synthetic data generated by the same shared
per-round latent-factor model the 2026-10-07 hazard artefact uses, and
reports ~0 under independence. AssertionError iff recovery fails."""
import random
import sys
import importlib.util as iu
from pathlib import Path

spec = iu.spec_from_file_location(
    "m", Path(__file__).resolve().parent / "measure_intra_round_correlation.py")
m = iu.module_from_spec(spec)
spec.loader.exec_module(m)

rng = random.Random(20261008)

def synth(rho, q=0.2, n_rounds=20000, seats=6):
    """Exchangeable binary seats: with prob rho the round's latent coin decides
    every seat identically; otherwise each seat flips independently. This makes
    corr(X_i, X_j) = rho exactly."""
    gs = []
    for _ in range(n_rounds):
        if rng.random() < rho:
            v = 1 if rng.random() < q else 0
            gs.append([v] * seats)
        else:
            gs.append([1 if rng.random() < q else 0 for _ in range(seats)])
    return gs

for rho in (0.0, 0.3, 0.5):
    gs = synth(rho)
    est_icc = m.icc1(gs)
    est_phi = m.pairwise_phi(gs)
    assert abs(est_icc - rho) < 0.03, f"FALSIFIED: ICC {est_icc} for true rho {rho}"
    assert abs(est_phi - rho) < 0.03, f"FALSIFIED: phi {est_phi} for true rho {rho}"
    print(f"true rho={rho}: ICC={est_icc:.4f} phi={est_phi:.4f}  recovered")

# Degenerate inputs are refused, not guessed.
assert m.icc1([[1, 0]]) is None
assert m.pairwise_phi([[1]]) is None
print("OK: estimator recovers known correlations and refuses degenerate input")
