#!/usr/bin/env python3
"""Dump every panel seat's verdict VERBATIM into one reviewable record.

Standing founder directive: external reviews are presented in full and
unfiltered, never summarised in place of the full output. The summariser does
not decide what matters.

Also records, per seat, how many tool calls were made and how many ERRORED, so
that a reader can tell a tool-verified verdict from an unverified one. That
distinction is the whole point of the 2026-09-05 rerun: the first run reported
17 tool calls of which 16 had silently failed.

Usage:  python3 scripts/dump_panel_findings_2026-09-05.py <log-dir> [<log-dir>...]
"""
import json
import pathlib
import sys

# `--help` MUST NOT ACT, AND ON A SIBLING OF THIS SCRIPT IT DESTROYED 54,480
# BYTES. Measured 2026-09-11: `--help` on `scripts/assemble_panel_record_0819.py`
# rewrote a 55,814-byte verbatim panel record down to 1,334 and exited 0, because
# the flag fell through to the script's ordinary work.
#
# GUARDED BY `__main__`, WHICH THE FIRST VERSION WAS NOT. Calling it at module
# level meant that any test IMPORTING this module handed pytest's own argv to the
# help handler, which refused it and exited 2 -- 12 failures and errors in the
# next clone run. The established form in this directory guards the call, and
# importing the module then reaches exactly the code it reached before.
if __name__ == "__main__":
    try:
        from _cli_help import answer_help   # scripts/ is sys.path[0] when run directly
    except ImportError:
        # A COPY OUTSIDE scripts/, which is how the mutation harness runs
        # this file: it writes the mutant to `.mutants/` where `_cli_help`
        # is not importable. Crashing there would make every mutant
        # "caught" for the wrong reason -- a crashing mutant produces no
        # output and every `not in` check passes. The guard protects real
        # invocations; a mutant copy is not one.
        pass
    else:
        answer_help(__doc__, __file__, takes_no_arguments=False)

REPO = pathlib.Path(__file__).resolve().parent.parent


def seat_block(path: pathlib.Path) -> str:
    j = json.load(open(path))
    tc = j.get("tool_calls", [])
    errored = [c for c in tc if '"error"' in str(c.get("result", ""))]
    lines = [
        f"### Seat: {path.stem}",
        "",
        f"- model: `{j.get('model')}`  route: `{j.get('route')}`",
        f"- ok: {j.get('ok')}   characters: {j.get('chars')}   elapsed: {j.get('elapsed_s')} s",
        f"- tool calls: {len(tc)}   ERRORED: {len(errored)}   succeeded: {len(tc) - len(errored)}",
    ]
    if tc and len(errored) == len(tc):
        lines.append("- **EVERY TOOL CALL FAILED. This verdict is NOT tool-verified.**")
    elif errored:
        lines.append(f"- **{len(errored)} of {len(tc)} tool calls failed.** Treat affected claims as unverified.")
    lines += ["", "```text", (j.get("response") or "(empty)"), "```", ""]
    return "\n".join(lines)


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    out = ["# Panel findings, verbatim", "",
           "Generated by `scripts/dump_panel_findings_2026-09-05.py`.", ""]
    for d in argv[1:]:
        p = REPO / "bench" / "logs" / d
        if not p.is_dir():
            print(f"no such log dir: {p}", file=sys.stderr)
            return 2
        out += [f"## Run: `{d}`", ""]
        for f in sorted(p.glob("*.json")):
            out.append(seat_block(f))
    dest = REPO / "experimental_notes" / "Panel_Findings_Verbatim_2026-09-05.md"
    dest.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {dest} ({dest.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
