#!/usr/bin/env python3
"""Dump every panel seat's verdict VERBATIM into one reviewable record.

Standing founder directive: external reviews are presented in full and
unfiltered, never summarised in place of the full output. The summariser does
not decide what matters.

Also records, per seat, how many tool calls were made and how many ERRORED, so
that a reader can tell a tool-verified verdict from an unverified one. That
distinction is the whole point of the 2026-09-05 rerun: the first run reported
17 tool calls of which 16 had silently failed.

Usage:  python3 scripts/dump_panel_findings_2026-09-05.py <log-dir> [<log-dir>...]
"""
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent


def seat_block(path: pathlib.Path) -> str:
    j = json.load(open(path))
    tc = j.get("tool_calls", [])
    errored = [c for c in tc if '"error"' in str(c.get("result", ""))]
    lines = [
        f"### Seat: {path.stem}",
        "",
        f"- model: `{j.get('model')}`  route: `{j.get('route')}`",
        f"- ok: {j.get('ok')}   characters: {j.get('chars')}   elapsed: {j.get('elapsed_s')} s",
        f"- tool calls: {len(tc)}   ERRORED: {len(errored)}   succeeded: {len(tc) - len(errored)}",
    ]
    if tc and len(errored) == len(tc):
        lines.append("- **EVERY TOOL CALL FAILED. This verdict is NOT tool-verified.**")
    elif errored:
        lines.append(f"- **{len(errored)} of {len(tc)} tool calls failed.** Treat affected claims as unverified.")
    lines += ["", "```text", (j.get("response") or "(empty)"), "```", ""]
    return "\n".join(lines)


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    out = ["# Panel findings, verbatim", "",
           "Generated by `scripts/dump_panel_findings_2026-09-05.py`.", ""]
    for d in argv[1:]:
        p = REPO / "bench" / "logs" / d
        if not p.is_dir():
            print(f"no such log dir: {p}", file=sys.stderr)
            return 2
        out += [f"## Run: `{d}`", ""]
        for f in sorted(p.glob("*.json")):
            out.append(seat_block(f))
    dest = REPO / "experimental_notes" / "Panel_Findings_Verbatim_2026-09-05.md"
    dest.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {dest} ({dest.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
